
=pod

=head1 METHODS

=head2 mbar ()

mfoo_purpose

=head2 mfoo ([ a => Int $a ], [ b => Str \$b ], c => Int|Str $c, [ d =>  $d ]) B<DEPRECATED>

Inherited from L<foo>

mfoo_purpose

B<Synopsis:>

        mfoo_example

B<Parameters:>

=over 4

=item * Int C<<< $a >>> (named, optional)

mfoo_a

=item * Str C<<< $b >>> (named, aliased, optional)

mfoo_b

=item * Int | Str C<<< $c >>> (named, required)

mfoo_c

=item *  C<<< $d >>> (named, optional, defaults to C<<<  2  >>>, but only when C<<<  { 1 == 0 } >>>)

=back

mfoo_pod1

mfoo_pod2

B<Returns:>

mfoo_returns

B<Throws:>

=over 4

=item * mfoo_throws1

=item * mfoo_throws2

=back

B<Available since:> mfoo_since

B<DEPRECATION WARNING:>

mfoo_deprecated

B<Author:> mfoo_author1, mfoo_author2

=head1 EXTENDS

=head2 bar

=over 4

=item * L<foo>

=back

=cut
